Repository sopra-fs24-group-26/server, pull requests merged in 2024-03, with the labels that each got.

#69 67: Proposition ReadMe.md pattern and workflow
  README.md
Labels: documentation, enhancement

#72 Clean up GitHub repository: Add pdf tile type and amount definition
  definition/TileType.pdf
Labels: documentation

#65 Initial logic and system architecture: Create rest controller and Session backend structure
  src/main/java/ch/uzh/ifi/hase/soprafs24/controller/Controller.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Player.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Session.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/repository/PlayerRepository.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/repository/SessionRepository.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/JoinDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/PlayerDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/PlayerService.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/SessionService.java
Labels: enhancement

#73 Initial logic and system architecture: Fix github workflows
  .github/workflows/main.yml
Labels: bug

#74 Fix sonarcloud
  .github/workflows/pr.yml
  settings.gradle
Labels: bug

#76 Initial Logic and System Architecture: Create tiles backend structure (service, entity, repository)
  src/main/java/ch/uzh/ifi/hase/soprafs24/controller/Controller.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Tile.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/repository/TileRepository.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/TileDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/TileIdTypeDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/TilePlaceDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/TileService.java
Labels: enhancement
